# Generated by Django 5.1.2 on 2024-10-15 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biology',
            name='confused_percentage',
        ),
    ]
