# Generated by Django 5.1.2 on 2024-10-15 06:53

import banjo.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_biology_confused_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='biology',
            name='confused_percentage',
            field=banjo.models.FloatField(default=0.0),
        ),
    ]
