# Generated by Django 5.1.2 on 2024-10-18 00:29

import banjo.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_biology_confused_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biology',
            name='confused',
            field=banjo.models.IntegerField(default=0),
        ),
    ]
